### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by manq2010**
Does my coding partner follow JS best practices?
---

In the release, the following was done:
* [x] Added a to-do list project that adds, remove and updates tasks

### CODE REVIEW

**Comment by KIsmoilov** [comment]
Hi @manq2010 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


### To highlight 💯 
- Good commit message ✔️ 
- No Linter errors ✔️ 
- Follow Github flow ✔️ 
- Very clean code on JavaScript ✔️ 

## Required Changes ♻️

- Please kindly avoid inserting SVG file codes inside your HTML element, which does not look nice. Instead, could you please images directory and create SVG file and paste your SVG codes there. 

- In order to follow [HTML&CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md) please to try avoid using _**!important**_ word in your CSS. 

- According to YAGNI rules, please avoid using empty HTML semantic elements such as: 

> <header></header>
> <footer></footer>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- It would be better if you can add **_a keypress event listener_** to your to-do list input field.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on @Rolandm99 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by manq2010** [comment]
hi @KIsmoilov, thanks for the feedback. I have made changes as suggested. Please let me know if all is well. Thanks

**Review by KIsmoilov — APPROVED** [review]
STATUS: APPROVED
---
giphy

Hi @manq2010. You did a good job by implementing the changes as requested. It's time to merge!

**Comment by manq2010** [comment]
Thanks @KIsmoilov.

**Pull request merged**
